# Generated by Django 5.2.4 on 2025-08-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_login_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
